### ISSUE TITLE
error with Eigen when running area_demand

### ISSUE THREAD

**Issue by ucsky** [TonyYenTWN/trEnD#1]
Hello,

When running the code on Ubuntu 20.04 after compiling with `g++ -g -Wall -o area_demand area_demand.cpp` I got the following error:

```area_demand: /usr/include/eigen3/Eigen/src/Core/Product.h:95: Eigen::Product<Lhs, Rhs, Option>::Product(const Lhs&, const Rhs&) [with _Lhs = Eigen::Matrix<double, -1, 1>; _Rhs = Eigen::Matrix<double, -1, 1>; int Option = 0; Eigen::Product<Lhs, Rhs, Option>::Lhs = Eigen::Matrix<double, -1, 1>; Eigen::Product<Lhs, Rhs, Option>::Rhs = Eigen::Matrix<double, -1, 1>]: Assertion `lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"' failed.```

How this could be fixed please?

**Comment by TonyYenTWN** [comment]
Thanks for bringing it up. I did not encounter this problem when compiling with  dev c++. I suspect the dimension of some of the matrix is wrong so there might be issue when matrix multiplication. I will inspect the issue thoroughly when I need to fine-tune the parameters for the electricity demand.

**Comment by TonyYenTWN** [comment]
Since the mentioned source file has been replaced in the latter version, I will close this issue.
